language: node_js
cache: npm
notifications:
  email: false
node_js:
  # technically we support 10.0.0, but some of our tooling doesn't
  - 10.14.2
  - 12
  - 14
  - 15
before_install:
  - nvm install-latest-npm
install:
  - npm install
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
